import React, { createContext, useState, useEffect } from 'react';

const translations = {
  ca: {
    // Navbar
    home: 'Inici',
    search: 'Buscar',
    publish: 'Publicar',
    profile: 'Perfil',
    login: 'Entrar',
    logout: 'Sortir',
    publish_car: 'Publicar cotxe',
    view_profile: 'Veure el meu perfil',
    logout_sidebar: 'Tancar sessió',
    
    // Footer
    tagline: 'La plataforma P2P de cotxes · Barcelona',
    about: 'Connectem propietaris de vehicles amb conductors de confiança. Sense intermediaris, sense comissions ocultes. Lloguer entre particulars fàcil, segur i a bon preu.',
    platform: 'Plataforma',
    search_car: 'Buscar cotxe',
    my_profile: 'El meu perfil',
    map_cars: 'Mapa de cotxes',
    info: 'Informació',
    how_it_works: 'Com funciona',
    security: 'Seguretat',
    insurance: 'Assegurança',
    faq: 'Preguntes freqüents',
    legal: 'Legal',
    terms: "Termes d'ús",
    privacy: 'Privacitat',
    cookies: 'Cookies',
    contact: 'Contacte',
    news: 'Novetats',
    news_desc: 'Rep ofertes exclusives i novetats de FlexiDrive directament al teu correu.',
    subscribe: "Subscriure's",
    no_spam: 'Sense spam',
    data_protected: 'Dades protegides',
    rights: 'Tots els drets reservats.',
    made_with: 'Fet amb ❤️ a Barcelona',
    ssl_verified: 'Verificat SSL',
    rgpd: 'RGPD compliant',
    
    // Profile
    tab_reservations: 'Reserves',
    tab_my_cars: 'Els meus cotxes',
    tab_favorites: 'Favorits',
    tab_stats: 'Estadístiques',
    tab_settings: 'Configuració',
    my_reservations: 'Les meves reserves',
    new_reservation: 'Nova reserva',
    all: 'Totes',
    actives: 'Actives',
    completed: 'Completades',
    cancelled: 'Cancel·lades',
    my_cars: 'Els meus cotxes',
    publish_first: 'Publicar el primer',
    publish_another: 'Publicar un altre cotxe',
    earn_up_to: 'Guanya fins a 450€/mes addicionals',
    my_favorites: 'Els meus favorits',
    cars_saved: 'cotxes guardats',
    explore_cars: 'Explorar cotxes',
    total_spent: 'Total gastat',
    total_earned: 'Total guanyat',
    total_reservations: 'Reserves totals',
    active_reservations: 'Reserves actives',
    recent_activity: 'Activitat recent',
    reservations_per_month: 'Reserves per mes (2026)',
    personal_data: 'Dades personals',
    personal_desc: 'Nom, email, telèfon',
    cancel: 'Cancel·lar',
    edit: 'Editar',
    full_name: 'Nom complet',
    phone: 'Telèfon',
    save_changes: 'Guardar canvis',
    notifications: 'Notificacions',
    notif_desc: 'Configura com vols rebre alertes',
    email_desc: 'Rebre confirmacions i alertes per email',
    push_desc: 'Notificacions del navegador en temps real',
    sms_desc: 'Missatges de text per a reserves urgents',
    security_tab: 'Seguretat',
    security_desc: 'Contrasenya i autenticació 2FA',
    payments: 'Mètodes de pagament',
    payments_desc: 'Targetes i compte bancari',
    lang_region: 'Idioma i regió',
    delete_account: 'Eliminar compte',
    delete_desc: 'Acció irreversible',
    
    // Home Screen (Core items)
    hero_title: 'FLEXIDRIVE',
    hero_subtitle: 'Reserva un cotxe a l\'instant, on siguis. De particulars per a particulars.',
    find_car: 'Buscar un cotxe',
    publish_mine: 'Publicar el meu',
    active_cars: 'Cotxes actius',
    average_rating: 'Valoració mitjana',
    availability: 'Disponibilitat',
    users: 'Usuaris',

    // Details & other items
    back: 'Tornar',
    available_now: 'Disponible ara',
    per_hour: 'per hora',
    any: 'Any',
    places: 'Places',
    combustible: 'Combustible',
    transmissio: 'Transmissió',
    min_reserva: 'Mín. reserva',
    alquileres: 'Alquileres',
    disponible: 'Disponible',
    valoracio: 'Valoració',
    descripcio: 'Descripció',
    verified_owner: 'Propietari verificat',
    vehicle_location: 'Ubicació del vehicle',
    insurance_included: 'Assegurança inclosa',
    insurance_desc: "Totes les reserves inclouen assegurança d'accidents i responsabilitat civil.",
    no_reviews: 'Encara no hi ha valoracions per aquest cotxe',
    anonymous: 'Anònim',
    pickup_time: 'Hora de recollida',
    duration: 'Durada',
    service_fee: 'Taxa de servei',
    total_label: 'Total',
    reserving_btn: 'RESERVANT...',
    reserve_now_btn: 'RESERVAR ARA',
    login_to_reserve_btn: 'INICIA SESSIÓ PER RESERVAR',
    booking_note: "No se't cobrarà res fins a la confirmació",
    secure_payment: 'Pagament segur',
    tab_info: 'Informació',
    tab_features: 'Equipament',
    tab_opinions: 'Opinions',
    km_away: 'km de tu',
    hours_plural: 'hores',
    hours_singular: 'hora',
    
    // New keys
    edit_vehicle: 'Editar vehicle',
    complete_booking: 'Completar reserva',
    complete_success: 'Reserva completada correctament!',
    edit_success: 'Vehicle actualitzat correctament!',
    stripe_payment_method: 'Mètode de pagament Stripe',
    stripe_card_desc: 'Introdueix les dades de la targeta per als cobraments i pagaments',
    stripe_card_number: 'Número de targeta',
    stripe_expiry: 'Data de caducitat',
    stripe_cvc: 'CVC',
    stripe_save: 'Desar targeta',
    stripe_success: 'Targeta guardada amb èxit!',
    billing_card: 'Targeta de facturació',
    last4: 'Últims 4 dígits'
  },
  es: {
    // Navbar
    home: 'Inicio',
    search: 'Buscar',
    publish: 'Publicar',
    profile: 'Perfil',
    login: 'Entrar',
    logout: 'Salir',
    publish_car: 'Publicar coche',
    view_profile: 'Ver mi perfil',
    logout_sidebar: 'Cerrar sesión',
    
    // Footer
    tagline: 'La plataforma P2P de coches · Barcelona',
    about: 'Conectamos propietarios de vehículos con conductores de confianza. Sin intermediarios, sin comisiones ocultas. Alquiler entre particulares fácil, seguro y a buen precio.',
    platform: 'Plataforma',
    search_car: 'Buscar coche',
    my_profile: 'Mi perfil',
    map_cars: 'Mapa de coches',
    info: 'Información',
    how_it_works: 'Cómo funciona',
    security: 'Seguridad',
    insurance: 'Seguro',
    faq: 'Preguntas frecuentes',
    legal: 'Legal',
    terms: 'Términos de uso',
    privacy: 'Privacidad',
    cookies: 'Cookies',
    contact: 'Contacto',
    news: 'Novedades',
    news_desc: 'Recibe ofertas exclusivas y novedades de FlexiDrive directamente en tu correo.',
    subscribe: 'Suscribirse',
    no_spam: 'Sin spam',
    data_protected: 'Datos protegidos',
    rights: 'Todos los derechos reservados.',
    made_with: 'Hecho con ❤️ en Barcelona',
    ssl_verified: 'Verificado SSL',
    rgpd: 'RGPD compliant',
    
    // Profile
    tab_reservations: 'Reservas',
    tab_my_cars: 'Mis coches',
    tab_favorites: 'Favoritos',
    tab_stats: 'Estadísticas',
    tab_settings: 'Configuración',
    my_reservations: 'Mis reservas',
    new_reservation: 'Nueva reserva',
    all: 'Todas',
    actives: 'Activas',
    completed: 'Completadas',
    cancelled: 'Canceladas',
    my_cars: 'Mis coches',
    publish_first: 'Publicar el primero',
    publish_another: 'Publicar otro coche',
    earn_up_to: 'Gana hasta 450€/mes adicionales',
    my_favorites: 'Mis favoritos',
    cars_saved: 'coches guardados',
    explore_cars: 'Explorar coches',
    total_spent: 'Total gastado',
    total_earned: 'Total ganado',
    total_reservations: 'Reservas totales',
    active_reservations: 'Reservas activas',
    recent_activity: 'Actividad reciente',
    reservations_per_month: 'Reservas por mes (2026)',
    personal_data: 'Datos personales',
    personal_desc: 'Nombre, email, teléfono',
    cancel: 'Cancelar',
    edit: 'Editar',
    full_name: 'Nombre completo',
    phone: 'Teléfono',
    save_changes: 'Guardar cambios',
    notifications: 'Notificaciones',
    notif_desc: 'Configura cómo quieres recibir alertas',
    email_desc: 'Recibir confirmaciones y alertas por email',
    push_desc: 'Notificaciones del navegador en tiempo real',
    sms_desc: 'Mensajes de texto para reservas urgentes',
    security_tab: 'Seguridad',
    security_desc: 'Contraseña y autenticación 2FA',
    payments: 'Métodos de pago',
    payments_desc: 'Tarjetas y cuenta bancaria',
    lang_region: 'Idioma y región',
    delete_account: 'Eliminar cuenta',
    delete_desc: 'Acción irreversible',
    
    // Home Screen (Core items)
    hero_title: 'FLEXIDRIVE',
    hero_subtitle: 'Reserva un coche al instante, donde estés. De particulares para particulares.',
    find_car: 'Buscar un coche',
    publish_mine: 'Publicar el mío',
    active_cars: 'Coches activos',
    average_rating: 'Valoración media',
    availability: 'Disponibilidad',
    users: 'Usuarios',

    // Details & other items
    back: 'Volver',
    available_now: 'Disponible ahora',
    per_hour: 'por hora',
    any: 'Año',
    places: 'Plazas',
    combustible: 'Combustible',
    transmissio: 'Transmisión',
    min_reserva: 'Mín. reserva',
    alquileres: 'Alquileres',
    disponible: 'Disponible',
    valoracio: 'Valoración',
    descripcio: 'Descripción',
    verified_owner: 'Propietario verificado',
    vehicle_location: 'Ubicación del vehículo',
    insurance_included: 'Seguro incluido',
    insurance_desc: 'Todas las reservas incluyen seguro de accidentes y responsabilidad civil.',
    no_reviews: 'Aún no hay valoraciones para este coche',
    anonymous: 'Anónimo',
    pickup_time: 'Hora de recogida',
    duration: 'Duración',
    service_fee: 'Tasa de servicio',
    total_label: 'Total',
    reserving_btn: 'RESERVANDO...',
    reserve_now_btn: 'RESERVAR AHORA',
    login_to_reserve_btn: 'INICIAR SESIÓN PARA RESERVAR',
    booking_note: 'No se te cobrará nada hasta la confirmación',
    secure_payment: 'Pago seguro',
    tab_info: 'Información',
    tab_features: 'Equipamiento',
    tab_opinions: 'Opiniones',
    km_away: 'km de ti',
    hours_plural: 'horas',
    hours_singular: 'hora',
    
    // New keys
    edit_vehicle: 'Editar vehículo',
    complete_booking: 'Completar reserva',
    complete_success: '¡Reserva completada correctamente!',
    edit_success: '¡Vehículo actualizado correctamente!',
    stripe_payment_method: 'Método de pago Stripe',
    stripe_card_desc: 'Introduce los datos de la tarjeta para los cobros y pagos',
    stripe_card_number: 'Número de tarjeta',
    stripe_expiry: 'Fecha de caducidad',
    stripe_cvc: 'CVC',
    stripe_save: 'Guardar tarjeta',
    stripe_success: '¡Tarjeta guardada con éxito!',
    billing_card: 'Tarjeta de facturación',
    last4: 'Últimos 4 dígitos'
  },
  en: {
    // Navbar
    home: 'Home',
    search: 'Search',
    publish: 'Publish',
    profile: 'Profile',
    login: 'Login',
    logout: 'Logout',
    publish_car: 'Publish Car',
    view_profile: 'View my Profile',
    logout_sidebar: 'Log out',
    
    // Footer
    tagline: 'The P2P Car Platform · Barcelona',
    about: 'We connect vehicle owners with trusted drivers. No middlemen, no hidden fees. Easy, safe, and affordable peer-to-peer car rental.',
    platform: 'Platform',
    search_car: 'Search Car',
    my_profile: 'My Profile',
    map_cars: 'Car Map',
    info: 'Information',
    how_it_works: 'How it works',
    security: 'Security',
    insurance: 'Insurance',
    faq: 'FAQs',
    legal: 'Legal',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    cookies: 'Cookies',
    contact: 'Contact',
    news: 'News',
    news_desc: 'Receive exclusive offers and FlexiDrive updates directly in your inbox.',
    subscribe: 'Subscribe',
    no_spam: 'No spam',
    data_protected: 'Data protected',
    rights: 'All rights reserved.',
    made_with: 'Made with ❤️ in Barcelona',
    ssl_verified: 'SSL Verified',
    rgpd: 'GDPR Compliant',
    
    // Profile
    tab_reservations: 'Bookings',
    tab_my_cars: 'My Cars',
    tab_favorites: 'Favorites',
    tab_stats: 'Statistics',
    tab_settings: 'Settings',
    my_reservations: 'My Bookings',
    new_reservation: 'New Booking',
    all: 'All',
    actives: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    my_cars: 'My Cars',
    publish_first: 'Publish the first one',
    publish_another: 'Publish another car',
    earn_up_to: 'Earn up to €450/month extra',
    my_favorites: 'My Favorites',
    cars_saved: 'cars saved',
    explore_cars: 'Explore Cars',
    total_spent: 'Total Spent',
    total_earned: 'Total Earned',
    total_reservations: 'Total Bookings',
    active_reservations: 'Active Bookings',
    recent_activity: 'Recent Activity',
    reservations_per_month: 'Bookings per month (2026)',
    personal_data: 'Personal Data',
    personal_desc: 'Name, email, phone',
    cancel: 'Cancel',
    edit: 'Edit',
    full_name: 'Full Name',
    phone: 'Phone',
    save_changes: 'Save Changes',
    notifications: 'Notifications',
    notif_desc: 'Configure how you want to receive alerts',
    email_desc: 'Receive confirmations and email alerts',
    push_desc: 'Real-time browser notifications',
    sms_desc: 'SMS messages for urgent bookings',
    security_tab: 'Security',
    security_desc: 'Password and 2FA authentication',
    payments: 'Payment Methods',
    payments_desc: 'Cards and bank account',
    lang_region: 'Language and Region',
    delete_account: 'Delete Account',
    delete_desc: 'Irreversible action',
    
    // Home Screen (Core items)
    hero_title: 'FLEXIDRIVE',
    hero_subtitle: 'Rent a car instantly, wherever you are. From individuals for individuals.',
    find_car: 'Find a Car',
    publish_mine: 'Publish Mine',
    active_cars: 'Active Cars',
    average_rating: 'Average Rating',
    availability: 'Availability',
    users: 'Users',

    // Details & other items
    back: 'Back',
    available_now: 'Available now',
    per_hour: 'per hour',
    any: 'Year',
    places: 'Seats',
    combustible: 'Fuel',
    transmissio: 'Transmission',
    min_reserva: 'Min. Booking',
    alquileres: 'Rentals',
    disponible: 'Available',
    valoracio: 'Rating',
    descripcio: 'Description',
    verified_owner: 'Verified Owner',
    vehicle_location: 'Vehicle Location',
    insurance_included: 'Insurance Included',
    insurance_desc: 'All bookings include third-party and accident insurance coverage.',
    no_reviews: 'No reviews yet for this car',
    anonymous: 'Anonymous',
    pickup_time: 'Pickup Time',
    duration: 'Duration',
    service_fee: 'Service Fee',
    total_label: 'Total',
    reserving_btn: 'BOOKING...',
    reserve_now_btn: 'BOOK NOW',
    login_to_reserve_btn: 'LOG IN TO BOOK',
    booking_note: 'You will not be charged anything until confirmation',
    secure_payment: 'Secure Payment',
    tab_info: 'Information',
    tab_features: 'Equipment',
    tab_opinions: 'Opinions',
    km_away: 'km from you',
    hours_plural: 'hours',
    hours_singular: 'hour',
    
    // New keys
    edit_vehicle: 'Edit Vehicle',
    complete_booking: 'Complete Booking',
    complete_success: 'Reservation completed successfully!',
    edit_success: 'Vehicle updated successfully!',
    stripe_payment_method: 'Stripe Payment Method',
    stripe_card_desc: 'Enter card details for charges and payments',
    stripe_card_number: 'Card Number',
    stripe_expiry: 'Expiry Date',
    stripe_cvc: 'CVC',
    stripe_save: 'Save Card',
    stripe_success: 'Card saved successfully!',
    billing_card: 'Billing Card',
    last4: 'Last 4 digits'
  }
};

export const LanguageContext = createContext({
  language: 'ca',
  setLanguage: () => {},
  t: () => {}
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('fd_language') || 'ca';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('fd_language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['ca']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
