import React, { createContext, useState, useEffect } from 'react';

const translations = {
  ca: {
    // Navbar
    home: 'Inici',
    search: 'Buscar',
    publish: 'Publicar',
    profile: 'Perfil',
    login: 'Entrar',
    logout: 'Sortir',
    publish_car: 'Publicar cotxe',
    view_profile: 'Veure el meu perfil',
    logout_sidebar: 'Tancar sessió',
    
    // Footer
    tagline: 'La plataforma P2P de cotxes · Barcelona',
    about: 'Connectem propietaris de vehicles amb conductors de confiança. Sense intermediaris, sense comissions ocultes. Lloguer entre particulars fàcil, segur i a bon preu.',
    platform: 'Plataforma',
    search_car: 'Buscar cotxe',
    my_profile: 'El meu perfil',
    map_cars: 'Mapa de cotxes',
    info: 'Informació',
    how_it_works: 'Com funciona',
    security: 'Seguretat',
    insurance: 'Assegurança',
    faq: 'Preguntes freqüents',
    legal: 'Legal',
    terms: "Termes d'ús",
    privacy: 'Privacitat',
    cookies: 'Cookies',
    contact: 'Contacte',
    news: 'Novetats',
    news_desc: 'Rep ofertes exclusives i novetats de FlexiDrive directament al teu correu.',
    subscribe: "Subscriure's",
    no_spam: 'Sense spam',
    data_protected: 'Dades protegides',
    rights: 'Tots els drets reservats.',
    made_with: 'Fet a Barcelona',
    ssl_verified: 'Verificat SSL',
    rgpd: 'RGPD compliant',
    
    // Profile
    tab_reservations: 'Reserves',
    tab_my_cars: 'Els meus cotxes',
    tab_favorites: 'Favorits',
    tab_stats: 'Estadístiques',
    tab_settings: 'Configuració',
    my_reservations: 'Les meves reserves',
    new_reservation: 'Nova reserva',
    all: 'Totes',
    actives: 'Actives',
    completed: 'Completades',
    cancelled: 'Cancel·lades',
    my_cars: 'Els meus cotxes',
    publish_first: 'Publicar el primer',
    publish_another: 'Publicar un altre cotxe',
    earn_up_to: 'Guanya fins a 450€/mes addicionals',
    my_favorites: 'Els meus favorits',
    cars_saved: 'cotxes guardats',
    explore_cars: 'Explorar cotxes',
    total_spent: 'Total gastat',
    total_earned: 'Total guanyat',
    total_reservations: 'Reserves totals',
    active_reservations: 'Reserves actives',
    recent_activity: 'Activitat recent',
    reservations_per_month: 'Reserves per mes (2026)',
    personal_data: 'Dades personals',
    personal_desc: 'Nom, email, telèfon',
    cancel: 'Cancel·lar',
    edit: 'Editar',
    full_name: 'Nom complet',
    phone: 'Telèfon',
    save_changes: 'Guardar canvis',
    notifications: 'Notificacions',
    notif_desc: 'Configura com vols rebre alertes',
    email_desc: 'Rebre confirmacions i alertes per email',
    push_desc: 'Notificacions del navegador en temps real',
    sms_desc: 'Missatges de text per a reserves urgents',
    security_tab: 'Seguretat',
    security_desc: 'Contrasenya i autenticació 2FA',
    payments: 'Mètodes de pagament',
    payments_desc: 'Targetes i compte bancari',
    lang_region: 'Idioma i regió',
    delete_account: 'Eliminar compte',
    delete_desc: 'Acció irreversible',
    
    // Home Screen (Core items)
    hero_title: 'FLEXIDRIVE',
    hero_subtitle: 'Reserva un cotxe a l\'instant, on siguis. De particulars per a particulars.',
    find_car: 'Buscar un cotxe',
    publish_mine: 'Publicar el meu',
    active_cars: 'Cotxes actius',
    average_rating: 'Valoració mitjana',
    availability: 'Disponibilitat',
    users: 'Usuaris',

    // Details & other items
    back: 'Tornar',
    available_now: 'Disponible ara',
    per_hour: 'per hora',
    any: 'Any',
    places: 'Places',
    combustible: 'Combustible',
    transmissio: 'Transmissió',
    min_reserva: 'Mín. reserva',
    alquileres: 'Alquileres',
    disponible: 'Disponible',
    valoracio: 'Valoració',
    descripcio: 'Descripció',
    verified_owner: 'Propietari verificat',
    vehicle_location: 'Ubicació del vehicle',
    insurance_included: 'Assegurança inclosa',
    insurance_desc: "Totes les reserves inclouen assegurança d'accidents i responsabilitat civil.",
    no_reviews: 'Encara no hi ha valoracions per aquest cotxe',
    anonymous: 'Anònim',
    pickup_time: 'Hora de recollida',
    duration: 'Durada',
    service_fee: 'Taxa de servei',
    total_label: 'Total',
    reserving_btn: 'RESERVANT...',
    reserve_now_btn: 'RESERVAR ARA',
    login_to_reserve_btn: 'INICIA SESSIÓ PER RESERVAR',
    booking_note: "No se't cobrarà res fins a la confirmació",
    secure_payment: 'Pagament segur',
    tab_info: 'Informació',
    tab_features: 'Equipament',
    tab_opinions: 'Opinions',
    km_away: 'km de tu',
    hours_plural: 'hores',
    hours_singular: 'hora',
    
    // New keys
    edit_vehicle: 'Editar vehicle',
    complete_booking: 'Completar reserva',
    complete_success: 'Reserva completada correctament!',
    edit_success: 'Vehicle actualitzat correctament!',
    stripe_payment_method: 'Mètode de pagament Stripe',
    stripe_card_desc: 'Introdueix les dades de la targeta per als cobraments i pagaments',
    stripe_card_number: 'Número de targeta',
    stripe_expiry: 'Data de caducitat',
    stripe_cvc: 'CVC',
    stripe_save: 'Desar targeta',
    stripe_success: 'Targeta guardada amb èxit!',
    billing_card: 'Targeta de facturació',
    last4: 'Últims 4 dígits',
    continue: 'Continuar',
    
    // Home Screen new keys
    location_label: 'Ubicació',
    search_placeholder: 'Zona, carrer o ciutat…',
    start_date: "Data d'inici",
    hours_label: 'Hores',
    all_day: 'Tot el dia',
    all_fuels: 'Tots',
    fuel_gasoline: 'Gasolina',
    fuel_diesel: 'Diésel',
    fuel_electric: 'Elèctric',
    fuel_hybrid: 'Híbrid',
    verified_owners: 'Propietaris verificats',
    real_reviews: 'Valoracions reals',
    secure_payment_desc: 'Transaccions protegides amb encriptació SSL',
    verified_owners_desc: 'Identitat i vehicle comprovats per FlexiDrive',
    real_reviews_desc: "Opinions verificades d'usuaris reals",
    featured_cars: 'Cotxes destacats',
    available_near_you: 'Disponibles ara prop de tu',
    view_all: 'Veure tots',
    three_steps: 'Tres passos per tenir el cotxe',
    step_search: 'Busca',
    step_search_desc: 'Troba cotxes disponibles a la teva zona al preu que vulguis. Filtra per combustible, transmissió i més.',
    step_reserve: 'Reserva',
    step_reserve_desc: 'Tria la franja horària i confirma la reserva en segons. Pagament segur integrat.',
    step_drive: 'Condueix',
    step_drive_desc: "Recull el cotxe, gaudeix i torna'l. Sense paperassa. L'assegurança va inclosa.",
    testimonials_title: 'El que diuen els usuaris',
    testimonials_subtitle: 'Més de 8.400 persones ja confien en FlexiDrive',
    explore_categories: 'Explora per categoria',
    explore_categories_subtitle: "Troba el cotxe que s'adapta a les teves necessitats",
    cat_electrics: 'Elèctrics',
    cat_hybrids: 'Híbrids',
    cat_suv: 'SUV / Familiars',
    cat_premium: 'Premium',
    cat_economy: 'Econòmics',
    cat_vans: 'Furgonetes',
    cat_available: 'disponibles',
    cta_title: 'Tens un cotxe aparcat?',
    cta_desc: 'Guanya diners deixant-lo quan no el fas servir. Fixes tu el preu i la disponibilitat. Sense comissions amagades.',
    cta_feat1: 'Configuració en 5 min',
    cta_feat2: 'Assegurança inclosa',
    cta_feat3: 'Pagament garantit',
    publish_mine_btn: 'Publicar el meu cotxe',
    estimated_earnings: 'Guanys estimats',
    per_month: 'mes',
    based_on_days: 'Basat en {days} dies/setmana · {price}€/h',
    test1_name: 'Joan Duran',
    test1_city: 'Barcelona',
    test1_text: 'Increïble! En 5 minuts tenia el cotxe reservat. El propietari era super amable i el vehicle estava impecable. Totalment recomanat!',
    test2_name: 'Sara Martí',
    test2_city: 'Gràcia',
    test2_text: 'He llogat 3 cotxes diferents i sempre ha estat perfecte. Els preus són molt millors que les empreses tradicionals. FlexiDrive és el futur!',
    test3_name: 'Pau Vidal',
    test3_city: 'Eixample',
    test3_text: 'Publico el meu cotxe des de fa 6 mesos i guanyo uns 300€ al mes extra. El procés és molt senzill i l\'equip de suport excel·lent.',
    
    // Search Screen new keys
    filters: 'Filtres',
    reset: 'Reiniciar',
    search_label: 'Cerca',
    max_price: 'Preu màxim',
    cars_available: 'cotxes disponibles',
    your_position: 'La teva posició',
    list_view: 'Llista',
    both_view: 'Ambdós',
    map_view: 'Mapa',
    sort_by: 'Ordenar per',
    distance: 'Distància',
    price: 'Preu',
    rating: 'Valoració',
    no_cars_match: 'Cap cotxe coincideix amb els filtres',
    reset_filters: 'Reiniciar filtres',
    searching_cars: 'Cercant cotxes...',
    available: 'Disponible',
    owner: 'Propietari',
    view: 'Veure',
    
    // Publish Screen new keys
    publish_title: 'Publica el teu cotxe',
    publish_subtitle: 'Comença a guanyar diners deixant el teu vehicle',
    step_vehicle: 'Vehicle',
    step_availability: 'Disponibilitat',
    step_price_photos: 'Preu i fotos',
    publish_success: 'Cotxe publicat correctament!',
    publish_btn: 'Publicar cotxe',
    publishing_btn: 'Publicant...',
    tips_title: 'Consells per guanyar més',
    tip1_title: 'Fotos de qualitat',
    tip1_desc: 'Els cotxes amb 5+ fotos reben 3x més reserves.',
    tip2_title: 'Preu competitiu',
    tip2_desc: 'Revisa preus similars a la teva zona.',
    tip3_title: 'Respon ràpid',
    tip3_desc: 'Els propietaris amb resposta <1h reben més valoracions positives.',
    use_current_location: 'Utilitzar ubicació actual',
    click_map_hint: 'Fes clic al mapa per ajustar la ubicació exacta',
    photos_label: 'Fotos del cotxe',
    drag_drop_hint: 'Arrossega o fes clic per pujar fotos',
    max_photos_limit: 'Màxim 8 fotos permeses',
    main_photo_badge: 'Principal',
    description_optional: 'Descripció (opcional)',
    description_placeholder: "Descriu el teu cotxe, característiques especials, normes d'ús…",
    min_hours_label: 'Preu mínim (hores)',
    price_per_hour_label: 'Preu per hora (€)',
    step_details_title: 'Dades del vehicle',
    make_model: 'Marca i model',
    matricula: 'Matrícula',
    year: 'Any',
    mileage_label: 'Quilometratge actual (km)',
    mileage_hint: 'Indica els km actuals del cotxe',
    seats_label: 'Places',
    fuel_label: 'Combustible',
    transmission_label: 'Canvi',
    car_location_label: 'Ubicació del cotxe',
    equipment_label: 'Equipament del vehicle',
    days_available_label: 'Dies disponibles',
    from_label: 'Des de',
    to_label: 'Fins a',
    preview_label: 'Vista prèvia',
    selected_count: 'seleccionats'
  },
  es: {
    // Navbar
    home: 'Inicio',
    search: 'Buscar',
    publish: 'Publicar',
    profile: 'Perfil',
    login: 'Entrar',
    logout: 'Salir',
    publish_car: 'Publicar coche',
    view_profile: 'Ver mi perfil',
    logout_sidebar: 'Cerrar sesión',
    
    // Footer
    tagline: 'La plataforma P2P de coches · Barcelona',
    about: 'Conectamos propietarios de vehículos con conductores de confianza. Sin intermediarios, sin comisiones ocultas. Alquiler entre particulares fácil, seguro y a buen precio.',
    platform: 'Plataforma',
    search_car: 'Buscar coche',
    my_profile: 'Mi perfil',
    map_cars: 'Mapa de coches',
    info: 'Información',
    how_it_works: 'Cómo funciona',
    security: 'Seguridad',
    insurance: 'Seguro',
    faq: 'Preguntas frecuentes',
    legal: 'Legal',
    terms: 'Términos de uso',
    privacy: 'Privacidad',
    cookies: 'Cookies',
    contact: 'Contacto',
    news: 'Novedades',
    news_desc: 'Recibe ofertas exclusivas y novedades de FlexiDrive directamente en tu correo.',
    subscribe: 'Suscribirse',
    no_spam: 'Sin spam',
    data_protected: 'Datos protegidos',
    rights: 'Todos los derechos reservados.',
    made_with: 'Hecho en Barcelona',
    ssl_verified: 'Verificado SSL',
    rgpd: 'RGPD compliant',
    
    // Profile
    tab_reservations: 'Reservas',
    tab_my_cars: 'Mis coches',
    tab_favorites: 'Favoritos',
    tab_stats: 'Estadísticas',
    tab_settings: 'Configuración',
    my_reservations: 'Mis reservas',
    new_reservation: 'Nueva reserva',
    all: 'Todas',
    actives: 'Activas',
    completed: 'Completadas',
    cancelled: 'Canceladas',
    my_cars: 'Mis coches',
    publish_first: 'Publicar el primero',
    publish_another: 'Publicar otro coche',
    earn_up_to: 'Gana hasta 450€/mes adicionales',
    my_favorites: 'Mis favoritos',
    cars_saved: 'coches guardados',
    explore_cars: 'Explorar coches',
    total_spent: 'Total gastado',
    total_earned: 'Total ganado',
    total_reservations: 'Reservas totales',
    active_reservations: 'Reservas activas',
    recent_activity: 'Actividad reciente',
    reservations_per_month: 'Reservas por mes (2026)',
    personal_data: 'Datos personales',
    personal_desc: 'Nombre, email, teléfono',
    cancel: 'Cancelar',
    edit: 'Editar',
    full_name: 'Nombre completo',
    phone: 'Teléfono',
    save_changes: 'Guardar cambios',
    notifications: 'Notificaciones',
    notif_desc: 'Configura cómo quieres recibir alertas',
    email_desc: 'Recibir confirmaciones y alertas por email',
    push_desc: 'Notificaciones del navegador en tiempo real',
    sms_desc: 'Mensajes de texto para reservas urgentes',
    security_tab: 'Seguridad',
    security_desc: 'Contraseña y autenticación 2FA',
    payments: 'Métodos de pago',
    payments_desc: 'Tarjetas y cuenta bancaria',
    lang_region: 'Idioma y región',
    delete_account: 'Eliminar cuenta',
    delete_desc: 'Acción irreversible',
    
    // Home Screen (Core items)
    hero_title: 'FLEXIDRIVE',
    hero_subtitle: 'Reserva un coche al instante, donde estés. De particulares para particulares.',
    find_car: 'Buscar un coche',
    publish_mine: 'Publicar el mío',
    active_cars: 'Coches activos',
    average_rating: 'Valoración media',
    availability: 'Disponibilidad',
    users: 'Usuarios',

    // Details & other items
    back: 'Volver',
    available_now: 'Disponible ahora',
    per_hour: 'por hora',
    any: 'Año',
    places: 'Plazas',
    combustible: 'Combustible',
    transmissio: 'Transmisión',
    min_reserva: 'Mín. reserva',
    alquileres: 'Alquileres',
    disponible: 'Disponible',
    valoracio: 'Valoración',
    descripcio: 'Descripción',
    verified_owner: 'Propietario verificado',
    vehicle_location: 'Ubicación del vehículo',
    insurance_included: 'Seguro incluido',
    insurance_desc: 'Todas las reservas incluyen seguro de accidentes y responsabilidad civil.',
    no_reviews: 'Aún no hay valoraciones para este coche',
    anonymous: 'Anónimo',
    pickup_time: 'Hora de recogida',
    duration: 'Duración',
    service_fee: 'Tasa de servicio',
    total_label: 'Total',
    reserving_btn: 'RESERVANDO...',
    reserve_now_btn: 'RESERVAR AHORA',
    login_to_reserve_btn: 'INICIAR SESIÓN PARA RESERVAR',
    booking_note: 'No se te cobrará nada hasta la confirmación',
    secure_payment: 'Pago seguro',
    tab_info: 'Información',
    tab_features: 'Equipamiento',
    tab_opinions: 'Opiniones',
    km_away: 'km de ti',
    hours_plural: 'horas',
    hours_singular: 'hora',
    
    // New keys
    edit_vehicle: 'Editar vehículo',
    complete_booking: 'Completar reserva',
    complete_success: '¡Reserva completada correctamente!',
    edit_success: '¡Vehículo actualizado correctamente!',
    stripe_payment_method: 'Método de pago Stripe',
    stripe_card_desc: 'Introduce los datos de la tarjeta para los cobros y pagos',
    stripe_card_number: 'Número de tarjeta',
    stripe_expiry: 'Fecha de caducidad',
    stripe_cvc: 'CVC',
    stripe_save: 'Guardar tarjeta',
    stripe_success: '¡Tarjeta guardada con éxito!',
    billing_card: 'Tarjeta de facturación',
    last4: 'Últimos 4 dígitos',
    continue: 'Continuar',
    
    // Home Screen new keys
    location_label: 'Ubicación',
    search_placeholder: 'Zona, calle o ciudad…',
    start_date: 'Fecha de inicio',
    hours_label: 'Horas',
    all_day: 'Todo el día',
    all_fuels: 'Todos',
    fuel_gasoline: 'Gasolina',
    fuel_diesel: 'Diésel',
    fuel_electric: 'Eléctrico',
    fuel_hybrid: 'Híbrido',
    verified_owners: 'Propietarios verificados',
    real_reviews: 'Valoraciones reales',
    secure_payment_desc: 'Transacciones protegidas con cifrado SSL',
    verified_owners_desc: 'Identidad y vehículo comprobados por FlexiDrive',
    real_reviews_desc: 'Opiniones verificadas de usuarios reales',
    featured_cars: 'Coches destacados',
    available_near_you: 'Disponibles ahora cerca de ti',
    view_all: 'Ver todos',
    three_steps: 'Tres pasos para tener el coche',
    step_search: 'Busca',
    step_search_desc: 'Encuentra coches disponibles en tu zona al precio que quieras. Filtra por combustible, transmisión y más.',
    step_reserve: 'Reserva',
    step_reserve_desc: 'Elige la franja horaria y confirma la reserva en segundos. Pago seguro integrado.',
    step_drive: 'Conduce',
    step_drive_desc: 'Recoge el coche, disfruta y devuélvelo. Sin papeleo. El seguro está incluido.',
    testimonials_title: 'Lo que dicen los usuarios',
    testimonials_subtitle: 'Más de 8.400 personas ya confían en FlexiDrive',
    explore_categories: 'Explora por categoría',
    explore_categories_subtitle: 'Encuentra el coche que se adapta a tus necesidades',
    cat_electrics: 'Eléctricos',
    cat_hybrids: 'Híbridos',
    cat_suv: 'SUV / Familiares',
    cat_premium: 'Premium',
    cat_economy: 'Económicos',
    cat_vans: 'Furgonetas',
    cat_available: 'disponibles',
    cta_title: '¿Tienes un coche aparcado?',
    cta_desc: 'Gana dinero alquilándolo cuando no lo uses. Eliges tú el precio y la disponibilidad. Sin comisiones ocultas.',
    cta_feat1: 'Configuración en 5 min',
    cta_feat2: 'Seguro incluido',
    cta_feat3: 'Pago garantizado',
    publish_mine_btn: 'Publicar mi coche',
    estimated_earnings: 'Ganancias estimadas',
    per_month: 'mes',
    based_on_days: 'Basado en {days} días/semana · {price}€/h',
    test1_name: 'Juan Durán',
    test1_city: 'Barcelona',
    test1_text: '¡Increíble! En 5 minutos tenía el coche reservado. El propietario era súper amable y el vehículo estaba impecable. ¡Totalmente recomendado!',
    test2_name: 'Sara Martí',
    test2_city: 'Gràcia',
    test2_text: 'He alquilado 3 coches diferentes y siempre ha sido perfecto. Los precios son mucho mejores que las empresas tradicionales. ¡FlexiDrive es el futuro!',
    test3_name: 'Pablo Vidal',
    test3_city: 'Eixample',
    test3_text: 'Publico mi coche desde hace 6 meses y gano unos 300€ al mes extra. El proceso es muy sencillo y el equipo de soporte excelente.',
    
    // Search Screen new keys
    filters: 'Filtros',
    reset: 'Reiniciar',
    search_label: 'Buscar',
    max_price: 'Precio máximo',
    cars_available: 'coches disponibles',
    your_position: 'Tu posición',
    list_view: 'Lista',
    both_view: 'Ambos',
    map_view: 'Mapa',
    sort_by: 'Ordenar por',
    distance: 'Distancia',
    price: 'Precio',
    rating: 'Valoración',
    no_cars_match: 'Ningún coche coincide con los filtros',
    reset_filters: 'Reiniciar filtros',
    searching_cars: 'Buscando coches...',
    available: 'Disponible',
    owner: 'Propietario',
    view: 'Ver',
    
    // Publish Screen new keys
    publish_title: 'Publica tu coche',
    publish_subtitle: 'Empieza a ganar dinero alquilando tu vehículo',
    step_vehicle: 'Vehículo',
    step_availability: 'Disponibilidad',
    step_price_photos: 'Precio y fotos',
    publish_success: '¡Coche publicado correctamente!',
    publish_btn: 'Publicar coche',
    publishing_btn: 'Publicando...',
    tips_title: 'Consejos para ganar más',
    tip1_title: 'Fotos de calidad',
    tip1_desc: 'Los coches con 5+ fotos reciben 3x más reservas.',
    tip2_title: 'Precio competitivo',
    tip2_desc: 'Revisa precios similares en tu zona.',
    tip3_title: 'Responde rápido',
    tip3_desc: 'Los propietarios con respuesta <1h reciben más valoraciones positivas.',
    use_current_location: 'Usar ubicación actual',
    click_map_hint: 'Haz clic en el mapa para ajustar la ubicación exacta',
    photos_label: 'Fotos del coche',
    drag_drop_hint: 'Arrastra o haz clic para subir fotos',
    max_photos_limit: 'Máximo 8 fotos permitidas',
    main_photo_badge: 'Principal',
    description_optional: 'Descripción (opcional)',
    description_placeholder: 'Describe tu coche, características especiales, normas de uso…',
    min_hours_label: 'Precio mínimo (horas)',
    price_per_hour_label: 'Precio por hora (€)',
    step_details_title: 'Datos del vehículo',
    make_model: 'Marca y modelo',
    matricula: 'Matrícula',
    year: 'Año',
    mileage_label: 'Kilometraje actual (km)',
    mileage_hint: 'Indica los km actuales del coche',
    seats_label: 'Plazas',
    fuel_label: 'Combustible',
    transmission_label: 'Cambio',
    car_location_label: 'Ubicación del coche',
    equipment_label: 'Equipamiento del vehículo',
    days_available_label: 'Días disponibles',
    from_label: 'Desde',
    to_label: 'Hasta',
    preview_label: 'Vista previa',
    selected_count: 'seleccionados'
  },
  en: {
    // Navbar
    home: 'Home',
    search: 'Search',
    publish: 'Publish',
    profile: 'Profile',
    login: 'Login',
    logout: 'Logout',
    publish_car: 'Publish Car',
    view_profile: 'View my Profile',
    logout_sidebar: 'Log out',
    
    // Footer
    tagline: 'The P2P Car Platform · Barcelona',
    about: 'We connect vehicle owners with trusted drivers. No middlemen, no hidden fees. Easy, safe, and affordable peer-to-peer car rental.',
    platform: 'Platform',
    search_car: 'Search Car',
    my_profile: 'My Profile',
    map_cars: 'Car Map',
    info: 'Information',
    how_it_works: 'How it works',
    security: 'Security',
    insurance: 'Insurance',
    faq: 'FAQs',
    legal: 'Legal',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    cookies: 'Cookies',
    contact: 'Contact',
    news: 'News',
    news_desc: 'Receive exclusive offers and FlexiDrive updates directly in your inbox.',
    subscribe: 'Subscribe',
    no_spam: 'No spam',
    data_protected: 'Data protected',
    rights: 'All rights reserved.',
    made_with: 'Made in Barcelona',
    ssl_verified: 'SSL Verified',
    rgpd: 'GDPR Compliant',
    
    // Profile
    tab_reservations: 'Bookings',
    tab_my_cars: 'My Cars',
    tab_favorites: 'Favorites',
    tab_stats: 'Statistics',
    tab_settings: 'Settings',
    my_reservations: 'My Bookings',
    new_reservation: 'New Booking',
    all: 'All',
    actives: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    my_cars: 'My Cars',
    publish_first: 'Publish the first one',
    publish_another: 'Publish another car',
    earn_up_to: 'Earn up to €450/month extra',
    my_favorites: 'My Favorites',
    cars_saved: 'cars saved',
    explore_cars: 'Explore Cars',
    total_spent: 'Total Spent',
    total_earned: 'Total Earned',
    total_reservations: 'Total Bookings',
    active_reservations: 'Active Bookings',
    recent_activity: 'Recent Activity',
    reservations_per_month: 'Bookings per month (2026)',
    personal_data: 'Personal Data',
    personal_desc: 'Name, email, phone',
    cancel: 'Cancel',
    edit: 'Edit',
    full_name: 'Full Name',
    phone: 'Phone',
    save_changes: 'Save Changes',
    notifications: 'Notifications',
    notif_desc: 'Configure how you want to receive alerts',
    email_desc: 'Receive confirmations and email alerts',
    push_desc: 'Real-time browser notifications',
    sms_desc: 'SMS messages for urgent bookings',
    security_tab: 'Security',
    security_desc: 'Password and 2FA authentication',
    payments: 'Payment Methods',
    payments_desc: 'Cards and bank account',
    lang_region: 'Language and Region',
    delete_account: 'Delete Account',
    delete_desc: 'Irreversible action',
    
    // Home Screen (Core items)
    hero_title: 'FLEXIDRIVE',
    hero_subtitle: 'Rent a car instantly, wherever you are. From individuals for individuals.',
    find_car: 'Find a Car',
    publish_mine: 'Publish Mine',
    active_cars: 'Active Cars',
    average_rating: 'Average Rating',
    availability: 'Availability',
    users: 'Users',

    // Details & other items
    back: 'Back',
    available_now: 'Available now',
    per_hour: 'per hour',
    any: 'Year',
    places: 'Seats',
    combustible: 'Fuel',
    transmissio: 'Transmission',
    min_reserva: 'Min. Booking',
    alquileres: 'Rentals',
    disponible: 'Available',
    valoracio: 'Rating',
    descripcio: 'Description',
    verified_owner: 'Verified Owner',
    vehicle_location: 'Vehicle Location',
    insurance_included: 'Insurance Included',
    insurance_desc: 'All bookings include third-party and accident insurance coverage.',
    no_reviews: 'No reviews yet for this car',
    anonymous: 'Anonymous',
    pickup_time: 'Pickup Time',
    duration: 'Duration',
    service_fee: 'Service Fee',
    total_label: 'Total',
    reserving_btn: 'BOOKING...',
    reserve_now_btn: 'BOOK NOW',
    login_to_reserve_btn: 'LOG IN TO BOOK',
    booking_note: 'You will not be charged anything until confirmation',
    secure_payment: 'Secure Payment',
    tab_info: 'Information',
    tab_features: 'Equipment',
    tab_opinions: 'Opinions',
    km_away: 'km from you',
    hours_plural: 'hours',
    hours_singular: 'hour',
    
    // New keys
    edit_vehicle: 'Edit Vehicle',
    complete_booking: 'Complete Booking',
    complete_success: 'Reservation completed successfully!',
    edit_success: 'Vehicle updated successfully!',
    stripe_payment_method: 'Stripe Payment Method',
    stripe_card_desc: 'Enter card details for charges and payments',
    stripe_card_number: 'Card Number',
    stripe_expiry: 'Expiry Date',
    stripe_cvc: 'CVC',
    stripe_save: 'Save Card',
    stripe_success: 'Card saved successfully!',
    billing_card: 'Billing Card',
    last4: 'Last 4 digits',
    continue: 'Continue',
    
    // Home Screen new keys
    location_label: 'Location',
    search_placeholder: 'Area, street or city…',
    start_date: 'Start date',
    hours_label: 'Hours',
    all_day: 'All day',
    all_fuels: 'All',
    fuel_gasoline: 'Gasoline',
    fuel_diesel: 'Diesel',
    fuel_electric: 'Electric',
    fuel_hybrid: 'Hybrid',
    verified_owners: 'Verified owners',
    real_reviews: 'Real reviews',
    secure_payment_desc: 'Transactions protected with SSL encryption',
    verified_owners_desc: 'Identity and vehicle verified by FlexiDrive',
    real_reviews_desc: 'Verified reviews from real users',
    featured_cars: 'Featured cars',
    available_near_you: 'Available now near you',
    view_all: 'View all',
    three_steps: 'Three steps to get the car',
    step_search: 'Search',
    step_search_desc: 'Find available cars in your area at the price you want. Filter by fuel, transmission and more.',
    step_reserve: 'Book',
    step_reserve_desc: 'Choose the time slot and confirm the booking in seconds. Secure payment integrated.',
    step_drive: 'Drive',
    step_drive_desc: 'Pick up the car, enjoy it and return it. No paperwork. Insurance is included.',
    testimonials_title: 'What users say',
    testimonials_subtitle: 'More than 8,400 people already trust FlexiDrive',
    explore_categories: 'Explore by category',
    explore_categories_subtitle: 'Find the car that fits your needs',
    cat_electrics: 'Electric',
    cat_hybrids: 'Hybrids',
    cat_suv: 'SUV / Families',
    cat_premium: 'Premium',
    cat_economy: 'Economy',
    cat_vans: 'Vans',
    cat_available: 'available',
    cta_title: 'Got a parked car?',
    cta_desc: 'Earn money by renting it out when you don\'t use it. You choose the price and availability. No hidden fees.',
    cta_feat1: 'Setup in 5 min',
    cta_feat2: 'Insurance included',
    cta_feat3: 'Payment guaranteed',
    publish_mine_btn: 'Publish my car',
    estimated_earnings: 'Estimated earnings',
    per_month: 'month',
    based_on_days: 'Based on {days} days/week · €{price}/h',
    test1_name: 'John Duran',
    test1_city: 'Barcelona',
    test1_text: 'Amazing! In 5 minutes I had the car booked. The owner was super friendly and the vehicle was spotless. Totally recommended!',
    test2_name: 'Sarah Marti',
    test2_city: 'Gracia',
    test2_text: 'I have rented 3 different cars and it has always been perfect. Prices are much better than traditional companies. FlexiDrive is the future!',
    test3_name: 'Paul Vidal',
    test3_city: 'Eixample',
    test3_text: 'I have been publishing my car for 6 months and earn about €300/month extra. The process is very simple and the support team is excellent.',
    
    // Search Screen new keys
    filters: 'Filters',
    reset: 'Reset',
    search_label: 'Search',
    max_price: 'Max price',
    cars_available: 'cars available',
    your_position: 'Your position',
    list_view: 'List',
    both_view: 'Both',
    map_view: 'Map',
    sort_by: 'Sort by',
    distance: 'Distance',
    price: 'Price',
    rating: 'Rating',
    no_cars_match: 'No cars match the filters',
    reset_filters: 'Reset filters',
    searching_cars: 'Searching cars...',
    available: 'Available',
    owner: 'Owner',
    view: 'View',
    
    // Publish Screen new keys
    publish_title: 'Publish your car',
    publish_subtitle: 'Start earning money by renting your vehicle',
    step_vehicle: 'Vehicle',
    step_availability: 'Availability',
    step_price_photos: 'Price & photos',
    publish_success: 'Car published successfully!',
    publish_btn: 'Publish car',
    publishing_btn: 'Publishing...',
    tips_title: 'Tips to earn more',
    tip1_title: 'Quality photos',
    tip1_desc: 'Cars with 5+ photos receive 3x more bookings.',
    tip2_title: 'Competitive price',
    tip2_desc: 'Check similar prices in your area.',
    tip3_title: 'Respond fast',
    tip3_desc: 'Owners with response <1h receive more positive reviews.',
    use_current_location: 'Use current location',
    click_map_hint: 'Click on the map to set the exact location',
    photos_label: 'Car photos',
    drag_drop_hint: 'Drag or click to upload photos',
    max_photos_limit: 'Maximum 8 photos allowed',
    main_photo_badge: 'Main',
    description_optional: 'Description (optional)',
    description_placeholder: 'Describe your car, special features, usage rules…',
    min_hours_label: 'Minimum booking (hours)',
    price_per_hour_label: 'Price per hour (€)',
    step_details_title: 'Vehicle details',
    make_model: 'Make and model',
    matricula: 'License plate',
    year: 'Year',
    mileage_label: 'Current mileage (km)',
    mileage_hint: 'Indicate current km of the car',
    seats_label: 'Seats',
    fuel_label: 'Fuel',
    transmission_label: 'Gearbox',
    car_location_label: 'Car location',
    equipment_label: 'Vehicle equipment',
    days_available_label: 'Available days',
    from_label: 'From',
    to_label: 'To',
    preview_label: 'Preview',
    selected_count: 'selected'
  }
};

export const LanguageContext = createContext({
  language: 'ca',
  setLanguage: () => {},
  t: () => {}
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('fd_language') || 'ca';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('fd_language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['ca']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
